package com.min.model;

// Generated 2018-8-2 19:01:10 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BizArticle generated by hbm2java
 */
@Entity
@Table(name = "biz_article", catalog = "blog")
public class BizArticle implements java.io.Serializable {

	private Long id;
	private String title;
	private long userId;
	private String coverImage;
	private String qrcodePath;
	private Boolean isMarkdown;
	private String content;
	private String contentMd;
	private Boolean top;
	private long typeId;
	private Boolean status;
	private Boolean recommended;
	private Boolean original;
	private String description;
	private String keywords;
	private Boolean comment;
	private Date createTime;
	private Date updateTime;

	public BizArticle() {
	}

	public BizArticle(long userId, long typeId) {
		this.userId = userId;
		this.typeId = typeId;
	}

	public BizArticle(String title, long userId, String coverImage,
			String qrcodePath, Boolean isMarkdown, String content,
			String contentMd, Boolean top, long typeId, Boolean status,
			Boolean recommended, Boolean original, String description,
			String keywords, Boolean comment, Date createTime, Date updateTime) {
		this.title = title;
		this.userId = userId;
		this.coverImage = coverImage;
		this.qrcodePath = qrcodePath;
		this.isMarkdown = isMarkdown;
		this.content = content;
		this.contentMd = contentMd;
		this.top = top;
		this.typeId = typeId;
		this.status = status;
		this.recommended = recommended;
		this.original = original;
		this.description = description;
		this.keywords = keywords;
		this.comment = comment;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "title")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "user_id", nullable = false)
	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	@Column(name = "cover_image")
	public String getCoverImage() {
		return this.coverImage;
	}

	public void setCoverImage(String coverImage) {
		this.coverImage = coverImage;
	}

	@Column(name = "qrcode_path")
	public String getQrcodePath() {
		return this.qrcodePath;
	}

	public void setQrcodePath(String qrcodePath) {
		this.qrcodePath = qrcodePath;
	}

	@Column(name = "is_markdown")
	public Boolean getIsMarkdown() {
		return this.isMarkdown;
	}

	public void setIsMarkdown(Boolean isMarkdown) {
		this.isMarkdown = isMarkdown;
	}

	@Column(name = "content")
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "content_md")
	public String getContentMd() {
		return this.contentMd;
	}

	public void setContentMd(String contentMd) {
		this.contentMd = contentMd;
	}

	@Column(name = "top")
	public Boolean getTop() {
		return this.top;
	}

	public void setTop(Boolean top) {
		this.top = top;
	}

	@Column(name = "type_id", nullable = false)
	public long getTypeId() {
		return this.typeId;
	}

	public void setTypeId(long typeId) {
		this.typeId = typeId;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Column(name = "recommended")
	public Boolean getRecommended() {
		return this.recommended;
	}

	public void setRecommended(Boolean recommended) {
		this.recommended = recommended;
	}

	@Column(name = "original")
	public Boolean getOriginal() {
		return this.original;
	}

	public void setOriginal(Boolean original) {
		this.original = original;
	}

	@Column(name = "description", length = 300)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "keywords", length = 200)
	public String getKeywords() {
		return this.keywords;
	}

	public void setKeywords(String keywords) {
		this.keywords = keywords;
	}

	@Column(name = "comment")
	public Boolean getComment() {
		return this.comment;
	}

	public void setComment(Boolean comment) {
		this.comment = comment;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
